version: '3'

services:
  client-backend:
    container_name: fields-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    depends_on:
      - database
    env_file:
      - .properties

  database:
    image: bitnami/postgresql:15
    container_name: fields-db
    env_file:
      - .properties
    ports:
      - "5434:5432"
    volumes:
      - pgdbdata:/var/lib/postgresql/data/
      - ./db-init:/docker-entrypoint-initdb.d

volumes:
  pgdbdata:

networks:
  default:
    external:
      name: agronetwork

